version: 0.2

env:
  variables:
    TF_VERSION: "0.12.28"

phases:
  install:
    commands:
      - mkdir download && cd download
  pre_build:
    commands:
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
  build:
    commands:
      - cd ..
      - mvn clean install
      - echo "Unit Test"
      - mvn test
      - cd terraform && terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - cd ..
      - echo "Intergation Test"
      - java -jar \
        -Ddb_name=dvdrental \
        -Dschema=public \
        -Doutput_file=. \
        -Ddatabase=jdbc:postgresql://localhost:5432/dvdrental \
        -Ddb_engine=postgres \
        -Ddriver_jar=../lib/9.1-901-1.jdbc4/postgresql-9.1-901-1.jdbc4.jar \
        -Ddriver_class=org.postgresql.Driver \
        -Dusername=postgres \
        -Dpassword=admin \
        target/schema-extractor-1.0.jar
      - sh scripts/validation.sh customer postgres
      - terraform destroy -auto-approve
# artifacts:
#   files:
#     - buildspec_rds.yml
#     - terraform/*