version: 0.2

env:
  variables:
    TF_VERSION: "0.12.28"

phases:
  install:
    commands:
      - mkdir download && cd download
  pre_build:
    commands:
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
  build:
    commands:
      - mvn clean install
      - mvn test
      - cd ../terraform && terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - terraform destroy -auto-approve
# artifacts:
#   files:
#     - buildspec_rds.yml
#     - terraform/*