version: 0.2

env:
  variables:
    TF_VERSION: "0.12.28"
    DS_SCHEMA: "information_schema"
    DS_TABLE: "sql_features"
phases:
  install:
    commands:
      - mkdir download && cd download
  pre_build:
    commands:
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip terraform_${TF_VERSION}_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
  build:
    commands:
      - cd ../terraform && terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - cd ..
      - echo "Intergation Test"
      - export DB_NAME=`terraform output rds_engine`
      - export DB_ENGINE=`terraform output rds_engine`
      - export DB_USER=`terraform output rds_user`
      - export DB_PASSWORD=`terraform output rds_password`
      - export DB_ENDPOINT=`terraform output rds_endpoint`
      - cd target/
      - java -jar \
        -Ddb_name=$DB_NAME \
        -Dschema=$DS_SCHEMA \
        -Doutput_file=../ \
        -Ddatabase=$DB_ENDPOINT \
        -Ddb_engine=$DB_ENGINE \
        -Ddriver_jar=/lib/postgresql-9.1-901-1.jdbc4.jar \
        -Ddriver_class=org.postgresql.Driver \
        -Dusername=$DB_USER \
        -Dpassword=$DB_PASSWORD \
        schema-extractor-1.0.jar
      - cd ..
      - sh scripts/validation.sh customer postgres
    finally:
      - cd terraform && terraform destroy -auto-approve
      - echo "Integration Test completed on:" `date`
